# build stage
FROM maven:3-jdk-8 as builder

ARG OBJECT_URL

ENV OBJECT_URL ${OBJECT_URL}

RUN mkdir -p /usr/src/app
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN mvn clean package

# run stage
FROM openjdk:8-jre-alpine

ARG RULES_PORT
ARG RULES_FLUENTD_HOST
ARG RULES_FLUENTD_PORT
ARG OBJECT_URL
ARG RULES_PROXY_HOSTNAME
ARG OAUTH2_ACCESS_TOKEN_URI
ARG OAUTH2_PROTECTED_URIS
ARG OAUTH2_CLIENT_ID
ARG OAUTH2_CLIENT_SECRET
ARG SSL_VERIFYING_DISABLE

ENV RULES_PORT ${RULES_PORT}
ENV RULES_FLUENTD_HOST ${RULES_FLUENTD_HOST}
ENV RULES_FLUENTD_PORT ${RULES_FLUENTD_PORT}
ENV OBJECT_URL ${OBJECT_URL}
ENV RULES_PROXY_HOSTNAME ${RULES_PROXY_HOSTNAME}
ENV OAUTH2_ACCESS_TOKEN_URI ${OAUTH2_ACCESS_TOKEN_URI}
ENV OAUTH2_PROTECTED_URIS ${OAUTH2_PROTECTED_URIS}
ENV OAUTH2_CLIENT_ID ${OAUTH2_CLIENT_ID}
ENV OAUTH2_CLIENT_SECRET ${OAUTH2_CLIENT_SECRET}
ENV SSL_VERIFYING_DISABLE ${SSL_VERIFYING_DISABLE}

COPY --from=builder /usr/src/app/target/fdns-ms-rules-*.jar /app.jar

# pull latest
RUN apk update && apk upgrade --no-cache

# don't run as root user
RUN chown 1001:0 /app.jar
RUN chmod g+rwx /app.jar
USER 1001

ENTRYPOINT java -Dserver.tomcat.protocol-header=x-forwarded-proto -Dserver.tomcat.remote-ip-header=x-forwarded-for -jar /app.jar